const api = "https://bank.gov.ua/NBUStatService/v1/statdirectory";

export const catalogue = [
  {
    number: 1,
    id: "exchange-rates",
    title:
      "Офіційний курс гривні до іноземних валют та СПЗ, облікова ціна банківських металів",
    category: "Ринки та борг",
    frequency: "щоденно",
    coverageStart: "1996",
    priority: "hero",
    status: "live",
    annualization: "середнє денних значень; кінець року доступний окремо",
    endpoint: "https://bank.gov.ua/NBU_Exchange/exchange_site",
  },
  {
    number: 2,
    id: "uonia",
    title: "Український індекс міжбанківських ставок овернайт (UONIA)",
    category: "Монетарна політика",
    frequency: "щоденно",
    coverageStart: "22.06.2020",
    priority: "hero",
    status: "live",
    annualization: "середнє доступних денних значень",
    endpoint: "https://bank.gov.ua/NBU_uonia?id_api=UONIA_UnsecLoansDepo",
  },
  {
    number: 3,
    id: "swap-index",
    title: "Довідковий індекс міжбанківських ставок за угодами своп",
    category: "Монетарна політика",
    frequency: "щоденно",
    coverageStart: "22.06.2020",
    priority: "top",
    status: "mapped",
    annualization: "середнє доступних денних значень",
    endpoint: "https://bank.gov.ua/NBU_uonia?id_api=REF-SWAP_Swaps",
  },
  {
    number: 4,
    id: "nbu-rates",
    title: "Оголошені процентні ставки за операціями Національного банку",
    category: "Монетарна політика",
    frequency: "щоденно",
    coverageStart: "25.06.1992",
    priority: "hero",
    status: "live",
    annualization: "значення на кінець року; поточне значення для неповного року",
    endpoint: `${api}/key?date=yyyymmdd`,
  },
  {
    number: 5,
    id: "ovdp-auctions",
    title: "Результати розміщення облігацій внутрішніх державних позик",
    category: "Ринки та борг",
    frequency: "за аукціоном",
    coverageStart: "першого запису API",
    priority: "hero",
    status: "mapped",
    annualization: "сума залучення та середньозважена дохідність за рік",
    endpoint: "https://bank.gov.ua/NBU_ovdp?json",
  },
  {
    number: 7,
    id: "loans",
    title: "Кредити, надані депозитними корпораціями",
    category: "Банківський сектор",
    frequency: "щомісячно",
    coverageStart: "08.2016",
    priority: "hero",
    status: "live",
    annualization: "залишок на кінець року",
    endpoint: `${api}/loan?date=yyyymmdd`,
  },
  {
    number: 8,
    id: "deposits",
    title: "Депозити, залучені депозитними корпораціями",
    category: "Банківський сектор",
    frequency: "щомісячно",
    coverageStart: "08.2016",
    priority: "hero",
    status: "live",
    annualization: "залишок на кінець року",
    endpoint: `${api}/deposit?date=yyyymmdd`,
  },
  {
    number: 9,
    id: "bank-securities",
    title:
      "Цінні папери та форми участі в капіталі в активах і зобов’язаннях депозитних корпорацій",
    category: "Банківський сектор",
    frequency: "щомісячно",
    coverageStart: "08.2016",
    priority: "deep",
    status: "mapped",
    annualization: "залишок на кінець року",
    endpoint: `${api}/securities?date=yyyymmdd`,
  },
  {
    number: 10,
    id: "bank-interest-rates",
    title: "Ставки за новими кредитами та новими депозитами",
    category: "Банківський сектор",
    frequency: "щомісячно",
    coverageStart: "08.2016",
    priority: "top",
    status: "mapped",
    annualization: "середньозважена річна ставка; обсяг операцій сумується",
    endpoint: `${api}/mir?date=yyyymmdd`,
  },
  {
    number: 11,
    id: "bank-income-expenses",
    title: "Доходи та витрати банків",
    category: "Банківський сектор",
    frequency: "місяць / квартал",
    coverageStart: "01.2009",
    priority: "top",
    status: "mapped",
    annualization: "грудневе кумулятивне значення, без повторного сумування",
    endpoint: `${api}/banksincexp?date=yyyymmdd&period=m`,
  },
  {
    number: 12,
    id: "bank-indicators",
    title: "Основні показники діяльності банків України",
    category: "Банківський сектор",
    frequency: "місяць / квартал",
    coverageStart: "12.2015",
    priority: "top",
    status: "mapped",
    annualization: "залишок або кількість на кінець року",
    endpoint: `${api}/basindbank?date=yyyymmdd&period=m`,
  },
  {
    number: 13,
    id: "bank-financial-statements",
    title: "Фінансова звітність та згруповані балансові залишки банків",
    category: "Банківський сектор",
    frequency: "місяць / квартал",
    coverageStart: "01.04.2012",
    priority: "deep",
    status: "mapped",
    annualization: "залишок на кінець року з контролем коригуючих проводок",
    endpoint: `${api}/banksfinrep?date=yyyymmdd&period=m`,
  },
  {
    number: 18,
    id: "business-surveys",
    title: "Опитування підприємств України",
    category: "Макроекономіка",
    frequency: "місяць / квартал",
    coverageStart: "I кв. 2015",
    priority: "top",
    status: "mapped",
    annualization: "середнє індексів за доступні періоди року",
    endpoint: `${api}/survey?period=m&date=yyyymmdd`,
  },
  {
    number: 19,
    id: "macro-indicators",
    title: "Макроекономічні показники",
    category: "Макроекономіка",
    frequency: "місяць / квартал / рік",
    coverageStart: "01.2003",
    priority: "hero",
    status: "live",
    annualization: "власна річна серія НБУ або правило за типом показника",
    endpoint: `${api}/inflation?period=y&date=yyyymm`,
  },
  {
    number: 20,
    id: "monetary-aggregates",
    title: "Грошові агрегати",
    category: "Монетарна політика",
    frequency: "щомісячно",
    coverageStart: "01.2003",
    priority: "hero",
    status: "live",
    annualization: "залишок на кінець року",
    endpoint: `${api}/monetary?date=yyyymmdd`,
  },
  {
    number: 21,
    id: "loans-by-debtor-class",
    title: "Розподіл кредитів фізичним та юридичним особам за класами боржника",
    category: "Банківський сектор",
    frequency: "щомісячно",
    coverageStart: "01.09.2017",
    priority: "top",
    status: "mapped",
    annualization: "залишок і кредитний ризик на кінець року",
    endpoint: `${api}/klk?date=yyyymmdd`,
  },
  {
    number: 22,
    id: "bank-account-turnover",
    title: "Обороти і залишки на рахунках банків",
    category: "Банківський сектор",
    frequency: "щомісячно",
    coverageStart: "01.2003",
    priority: "deep",
    status: "mapped",
    annualization: "обороти сумуються; залишки беруться на кінець року",
    endpoint: `${api}/osb?date=yyyymmdd`,
  },
  {
    number: 23,
    id: "financial-corporation-surveys",
    title: "Огляди фінансових корпорацій",
    category: "Монетарна політика",
    frequency: "місяць / квартал",
    coverageStart: "12.2002",
    priority: "top",
    status: "mapped",
    annualization: "залишок на кінець року",
    endpoint: `${api}/depcornbu?date=yyyymmdd`,
  },
  {
    number: 24,
    id: "international-reserves",
    title: "Міжнародні резерви",
    category: "Зовнішній сектор",
    frequency: "щомісячно",
    coverageStart: "12.2002",
    priority: "hero",
    status: "live",
    annualization: "залишок на кінець року",
    endpoint: `${api}/res?date=yyyymm`,
  },
  {
    number: 27,
    id: "balance-of-payments",
    title: "Платіжний баланс України",
    category: "Зовнішній сектор",
    frequency: "щомісячно",
    coverageStart: "01.2010",
    priority: "hero",
    status: "mapped",
    annualization: "сума некумулятивних місячних потоків за рік",
    endpoint: `${api}/balanceofpayments?start=yyyymmdd&end=yyyymmdd`,
  },
  {
    number: 28,
    id: "international-investment-position",
    title: "Міжнародна інвестиційна позиція України",
    category: "Зовнішній сектор",
    frequency: "щоквартально",
    coverageStart: "кінець 2001",
    priority: "top",
    status: "mapped",
    annualization: "позиція на кінець IV кварталу",
    endpoint: `${api}/interinvestpos?date=yyyymm`,
  },
  {
    number: 29,
    id: "foreign-direct-investment",
    title: "Прямі інвестиції",
    category: "Зовнішній сектор",
    frequency: "щоквартально",
    coverageStart: "I кв. 2015",
    priority: "hero",
    status: "mapped",
    annualization: "запаси на кінець року; потоки сумуються",
    endpoint: `${api}/fdis?json`,
  },
  {
    number: 30,
    id: "gross-external-debt",
    title: "Валовий зовнішній борг України",
    category: "Зовнішній сектор",
    frequency: "щоквартально",
    coverageStart: "IV кв. 2003",
    priority: "hero",
    status: "mapped",
    annualization: "позиція на кінець IV кварталу",
    endpoint: `${api}/grossextdebt?date=yyyymm`,
  },
  {
    number: 31,
    id: "short-term-external-debt",
    title: "Короткостроковий зовнішній борг за залишковим терміном погашення",
    category: "Зовнішній сектор",
    frequency: "щоквартально",
    coverageStart: "IV кв. 2003",
    priority: "top",
    status: "mapped",
    annualization: "позиція на кінець IV кварталу",
    endpoint: `${api}/shotextdebt?date=yyyymm`,
  },
  {
    number: 32,
    id: "fx-market",
    title: "Показники валютного ринку",
    category: "Ринки та борг",
    frequency: "день / місяць",
    coverageStart: "2017",
    priority: "hero",
    status: "mapped",
    annualization: "інтервенції сумуються; курсові показники усереднюються",
    endpoint: `${api}/kursf?date=yyyymmdd&period=d`,
  },
  {
    number: 33,
    id: "cash-fx-flows",
    title: "Ввезення та вивезення готівкової іноземної валюти банками",
    category: "Зовнішній сектор",
    frequency: "місяць / рік",
    coverageStart: "01.2012",
    priority: "deep",
    status: "mapped",
    annualization: "власний річний набір НБУ; місячні потоки сумуються",
    endpoint: `${api}/casflow?date=yyyymmdd&period=Y`,
  },
];
