export const metricRegistry = [
  {
    id: "fx_usd",
    title: "Офіційний курс USD/UAH",
    shortTitle: "USD / UAH",
    category: "Ринки та борг",
    unit: "грн за 1 USD",
    format: "decimal",
    color: "#0057b8",
    coverageStart: "1996",
    annualization: "Середнє офіційних денних курсів",
  },
  {
    id: "policy_rate",
    title: "Облікова ставка НБУ",
    shortTitle: "Облікова ставка",
    category: "Монетарна політика",
    unit: "% річних",
    format: "percent",
    color: "#c92f2f",
    coverageStart: "25.06.1992",
    annualization: "Значення на кінець року",
  },
  {
    id: "uonia",
    title: "Український індекс міжбанківських ставок овернайт",
    shortTitle: "UONIA",
    category: "Монетарна політика",
    unit: "% річних",
    format: "percent",
    color: "#e66a2c",
    coverageStart: "22.06.2020",
    annualization: "Середнє доступних денних значень",
  },
  {
    id: "reserves",
    title: "Офіційні міжнародні резерви",
    shortTitle: "Резерви",
    category: "Зовнішній сектор",
    unit: "млн дол. США",
    format: "usd_billion",
    color: "#5f704f",
    coverageStart: "12.2002",
    annualization: "Залишок на кінець року",
  },
  {
    id: "m3",
    title: "Грошовий агрегат M3",
    shortTitle: "Грошова маса M3",
    category: "Монетарна політика",
    unit: "млн грн",
    format: "uah_billion",
    color: "#0057b8",
    coverageStart: "01.2003",
    annualization: "Залишок на кінець року",
  },
  {
    id: "loans",
    title: "Кредити резидентам",
    shortTitle: "Кредити",
    category: "Банківський сектор",
    unit: "млн грн",
    format: "uah_billion",
    color: "#c92f2f",
    coverageStart: "08.2016",
    annualization: "Залишок на кінець року",
  },
  {
    id: "deposits",
    title: "Депозити резидентів",
    shortTitle: "Депозити",
    category: "Банківський сектор",
    unit: "млн грн",
    format: "uah_billion",
    color: "#5f704f",
    coverageStart: "08.2016",
    annualization: "Залишок на кінець року",
  },
  {
    id: "inflation",
    title: "Індекс споживчих цін",
    shortTitle: "Інфляція р/р",
    category: "Макроекономіка",
    unit: "%",
    format: "percent",
    color: "#e66a2c",
    coverageStart: "01.2007",
    annualization: "Грудень до грудня попереднього року",
  },
];
